var vi_language = {
    a1DaThemVaoYeuThich: "Đã thêm vào yêu thích",
    a2PhaiNhapEmail: "Vui lòng nhập mail!",
    a3KhongDuocDeTrong: "Không được để trống!",
    a4MaXacNhanSai: "Mã xác nhận sai!",
    a5HayNhapDungSDT: "Vui lòng nhập đúng số điện thoại!",
    a6HayDienDayDuThongTin: "Hãy điền đầy đủ thông tin!",
    a7EmailDaSuDung: "Email đã được sử dụng",
    a8BanChuaChapNhanDieuKhoanDichVu: "Vui lòng chấp nhận điều khoản dịch vụ!",
    a9SoChoToiDaChoChon: "Số chổ tối đa cho chọn: ",
    a10Cho: "chổ",
    a11BanChuaChonVe: "Bạn chưa chọn vé!",
    a12BanChuaChonVeDi: 'Bạn chưa chọn vé đi',
    a13BanPhaiNhapThongTinNguoiDaiDien: 'Bạn phải nhập đủ thông tin khách đầu tiên(Người Đaị Diện)',
    a14VuiLongNhapTen: "Vui lòng nhập tên",
    a15VuiLongNhapMatKhau: "Vui lòng nhập mật khẩu",
    a16VuiLongChonThanhPho: "Vui lòng chọn thành phố",
    a17VuiLongChonQuan: "Vui lòng chọn quận",
    a18VuiLongChonPhuong: "Vui lòng chọn phường",
    a19BatBuocNhapSoNha: "Vui lòng nhập địa chỉ",
    a20VuiLongNhapSDT: "Vui lòng nhập số điện thoại",
    a21PleaseEnterEmail: "Vui lòng nhập email",
    a22TourHetCho: "Tour đã hết chỗ, Vui lòng liên hệ với Du Lịch Việt để được hỗ trợ!",
    a23HayDienVaChapNhanDieuKhoanDichVu: "Bạn phải điều đủ thông tin và chấp nhận điều khoản dịch vụ!"
};

var en_language = {
    a1DaThemVaoYeuThich: "Added to favorite",
    a2PhaiNhapEmail: "Email required!",
    a3KhongDuocDeTrong: "Field required!",
    a4MaXacNhanSai: "Wrong Security code!",
    a5HayNhapDungSDT: "Phonenumber required!",
    a6HayDienDayDuThongTin: "Please fill all the field!",
    a7EmailDaSuDung: "Email is already used",
    a8BanChuaChapNhanDieuKhoanDichVu: "You need to accept term and policy!",
    a9SoChoToiDaChoChon: "Maximum seat left: ",
    a10Cho: "seat",
    a11BanChuaChonVe: "You need to pick ticket to continue!",
    a12BanChuaChonVeDi: 'You need to pick depart ticket',
    a13BanPhaiNhapThongTinNguoiDaiDien: 'You Have To Fill The First Section(Contact Person)',
    a14VuiLongNhapTen: "Please enter name",
    a15VuiLongNhapMatKhau: "Please enter password",
    a16VuiLongChonThanhPho: "Please select your city",
    a17VuiLongChonQuan: "Please select district",
    a18VuiLongChonPhuong: "Please select ward",
    a19BatBuocNhapSoNha: "Please enter address",
    a20VuiLongNhapSDT: "Please enter phone number",
    a21PleaseEnterEmail: "Please enter email",
    a22TourHetCho: "Tour is sold out, Please contact us for more support!",
    a23HayDienVaChapNhanDieuKhoanDichVu: "You need to accept term and policy, fill up all info!"
};

